### ISSUE TITLE
cohesity_agent - state: present does no upgrade of installed agent

### ISSUE THREAD

**Issue by kortstie** [cohesity/cohesity-ansible-role#13]
Hi Cohesity!

an installed and running Cohesity Agent Version 6.0.0.a is not upgraded when the role cohesity_agent is running on the host.
It would be helpful if the role detects and upgrades an older installed version of the client.

Best Regards

Frank

**Comment by goodrum** [comment]
Frank,

This is slated for a future update.  Thank you for bringing this up.  The plan would be to support a _should-upgrade_ parameter as a Boolean.  This would allow you to override the process of _Is this installed_ to support an _upgrade to latest_.  

The decision was to add this later since you can manage the agent upgrades directly from the Cohesity UI but we agree that this is an important feature.

**Comment by naveena-maplelabs** [comment]
Support for Cohesity Agent upgrade is available in the new releases(v2.3.4) and for more enhancements use cohesity [collections](https://galaxy.ansible.com/cohesity/dataprotect).
